name: Deploy master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        node-version: 18.x
    - name: Run ls command
      run: |
        ls
    - name: npm install and npm run build
      run: |
        npm install --legacy-peer-deps --force && npm run build
    - name: Run ls command
      run: |
        ls 
    - name: Zip artifact for deployment
      run: |
        cp Procfile package.json dist/eshop-app
        cd dist/eshop-app
        zip -r release.zip ./*
        mv release.zip /home/runner/work/Final-frontend-angular/Final-frontend-angular/
        ls /home/runner/work/Final-frontend-angular/Final-frontend-angular/
