name: Deploy master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies and build
      run: |
        npm install
        npm ci
        npm install -g npm-check-updates
        npm run build
        
    - name: Zip artifact for deployment
      run: |
        cp /home/runner/work/Final-frontend-angular/Final-frontend-angular/package.json /home/runner/work/Final-frontend-angular/Final-frontend-angular/dist/eshop-app
        cd  dist/eshop-app
        zip release.zip ./* -r
        ls
        mv release.zip /home/runner/work/Final-frontend-angular/Final-frontend-angular
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: release.zip
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v1
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Eshopfrontend
        environment_name: Eshopfrontend-env
        version_label: ${{ github.run_id }}
        region: us-east-1
        deployment_package: release.zip
