name: Deploy master
on:
  push:
    branches:
      - master
#ab
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        node-version: 12.x
    - name: Run ls command
      run: |
        dir 
    - name: Install dependencies
      run: |
        npm install
        npm i angular-responsive-carousel --force
        npm install eslint
        npm install webpack
        npm run build
    - name: ls
      run: ls

