name: Deploy master
on:
  push:
    branches:
      - master
#ab
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        node-version: 16.x
    - name: Run ls command
      run: |
        dir 
    - name: Install dependencies
      run: |
        npm install
        npm i angular-responsive-carousel --force
        npm run build
    - name: Run ls command
      run: |
        ls D:\a\Final-frontend-angular\Final-frontend-angular\dist\eshop-app\
    - name: Zip artifact for deployment
      run: Compress-Archive -Path D:\a\Final-frontend-angular\Final-frontend-angular\dist\eshop-app\* -Destination eshop-app.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: eshop-app.zip
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v1
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Eshopfrontend
          environment_name: Eshopfrontend-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: eshop-app.zip
        


