name: Deploy master
on:
  push:
    branches:
      - master
#ab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        node-version: 16.x
    - name: Run ls command
      run: |
        ls
    - name: npm install and npm run build
      run: |
          npm install -g npm-check-updates
          ncu -u
          npm install --legacy-peer-deps --force && npm run build
    - name: Run ls command
      run: |
        ls 
    - name: Zip artifact for deployment
      run: |
        cp /home/runner/work/Final-frontend-angular/Final-frontend-angular/package.json /home/runner/work/Final-frontend-angular/Final-frontend-angular/dist/eshop-app
        cd  dist/eshop-app
        zip release.zip ./* -r
        ls
        mv release.zip /home/runner/work/Final-frontend-angular/Final-frontend-angular
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: release.zip
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v1
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Eshopfrontend
          environment_name: Eshopfrontend-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: release.zip
   
 

