name: Deploy master
on:
  push:
    branches:
      - master
#ab
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        node-version: 12.x
    - name: Run ls command
      run: |
        dir 
    - name: Install dependencies
      run: |
        npm install
        npm i angular-responsive-carousel --force
        npm install eslint
        npm install webpack
        npm run build
    - name: Run ls command
      run: |
        ls D:\a\Final-frontend-angular\Final-frontend-angular\dist\
    - name: Zip artifact for deployment
      run: Compress-Archive -Path D:\a\Final-frontend-angular\Final-frontend-angular\dist\* -Destination Release.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: dist.zip

